server:
  port: 8082
spring:
  application:
    name: "IdentifyMutant"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null


dynamodb:
  tbl-name:
    human: human
